# Generated by Django 2.2.4 on 2019-08-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EveryDayMotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(default='Rie fu', max_length=100, verbose_name='Motto')),
                ('author', models.CharField(default='Life is like a boat', max_length=50, verbose_name='Author')),
                ('poster', models.ImageField(upload_to='../media/motto/poster', verbose_name='poster')),
                ('audio', models.FileField(upload_to='../media/motto/audio', verbose_name='poster')),
            ],
        ),
    ]
