# Generated by Django 2.2.4 on 2019-08-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydaymotto',
            name='author',
            field=models.CharField(default='Rie fu', max_length=50, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='everydaymotto',
            name='motto',
            field=models.CharField(default='Life is like a boat', max_length=100, verbose_name='Motto'),
        ),
    ]
