# Generated by Django 2.2.4 on 2019-08-24 08:17

import Kaldi_speech.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0002_auto_20190824_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('intro', models.CharField(max_length=200, verbose_name='introduction')),
                ('num_sections', models.IntegerField(verbose_name='sections')),
                ('course_img', models.ImageField(upload_to='../media/course/course_img', verbose_name='poster')),
                ('num_learners', models.IntegerField(verbose_name='learners')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='add time')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('subtitle', models.CharField(max_length=200, verbose_name='subtitle')),
                ('num_sentences', models.IntegerField(verbose_name='sentences')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_en', models.CharField(max_length=200, verbose_name='English')),
                ('sentence_ch', models.CharField(max_length=200, verbose_name='Chinese')),
                ('sentence_src', models.FileField(upload_to=Kaldi_speech.models.section_directory_path, verbose_name='audio')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.Section')),
            ],
        ),
    ]
