# Generated by Django 2.2.4 on 2019-08-24 08:29

import Kaldi_speech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0003_course_section_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(upload_to=Kaldi_speech.models.course_directory_path, verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='course',
            name='num_learners',
            field=models.IntegerField(default=0, verbose_name='learners'),
        ),
    ]
