# Generated by Django 2.2.4 on 2019-08-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0010_auto_20190824_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydaymotto',
            name='audio',
            field=models.FileField(default='default.wav', upload_to='../media/motto/audio', verbose_name='audio'),
        ),
    ]
