# Generated by Django 2.2.4 on 2019-08-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0011_auto_20190824_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydaymotto',
            name='audio',
            field=models.FileField(default='/motto/audio/default.wav', upload_to='motto/audio', verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='everydaymotto',
            name='poster',
            field=models.ImageField(upload_to='motto/poster', verbose_name='poster'),
        ),
    ]
