# Generated by Django 2.2.4 on 2019-08-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0012_auto_20190824_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydaymotto',
            name='audio',
            field=models.FileField(default='motto/audio/default.wav', upload_to='motto/audio', verbose_name='audio'),
        ),
    ]
