# Generated by Django 2.2.4 on 2019-08-24 09:14

import Kaldi_speech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0014_auto_20190824_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydaymotto',
            name='audio',
            field=models.FileField(upload_to='motto/audio', verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='everydaymotto',
            name='poster',
            field=models.ImageField(upload_to='motto/poster', verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence_src',
            field=models.FileField(upload_to=Kaldi_speech.models.section_directory_path, verbose_name='audio'),
        ),
    ]
