# Generated by Django 2.2.2 on 2019-08-28 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0015_auto_20190824_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=50, verbose_name='vocabulary')),
                ('uk_phonetic', models.CharField(max_length=100, verbose_name='uk phonetic')),
                ('us_phonetic', models.CharField(max_length=100, verbose_name='us phonetic')),
                ('uk_speech', models.FileField(upload_to='verb/', verbose_name='uk speech')),
                ('us_speech', models.FileField(upload_to='verb/', verbose_name='us speech')),
            ],
        ),
        migrations.CreateModel(
            name='VerbExplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=20, verbose_name='part of speech')),
                ('explain', models.CharField(max_length=200, verbose_name='explain')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.Verb')),
            ],
        ),
    ]
