# Generated by Django 2.2.4 on 2019-08-29 13:47

import Kaldi_speech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0016_verb_verbexplain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence_src',
            field=models.FileField(default='default/default.wav', upload_to=Kaldi_speech.models.section_directory_path, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='us_phonetic',
            field=models.CharField(default='default/default.wav', max_length=100, verbose_name='us phonetic'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='us_speech',
            field=models.FileField(default='default/default.wav', upload_to='verb/', verbose_name='us speech'),
        ),
    ]
