# Generated by Django 2.2.4 on 2019-08-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0018_auto_20190829_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_sections',
            field=models.IntegerField(default=0, verbose_name='sections'),
        ),
        migrations.AlterField(
            model_name='section',
            name='num_sentences',
            field=models.IntegerField(default=0, verbose_name='sentences'),
        ),
    ]
