# Generated by Django 2.2.4 on 2019-08-31 05:11

import Kaldi_speech.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0019_auto_20190830_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=100, verbose_name='user open id')),
                ('learn_days', models.DateField(auto_now_add=True, verbose_name='add time')),
            ],
        ),
        migrations.CreateModel(
            name='UserVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.User')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.Verb')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_sentence', models.IntegerField(default=0, verbose_name='current sentence')),
                ('audio', models.FileField(default='default/default.wav', upload_to=Kaldi_speech.models.useraudio_directory_path, verbose_name='user audio')),
                ('score', models.IntegerField(default=90, verbose_name='score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.User')),
            ],
        ),
    ]
