# Generated by Django 2.2.4 on 2019-08-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0020_user_usercourse_userverb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='curr_sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.Sentence'),
        ),
    ]
