# Generated by Django 2.2.4 on 2019-08-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0021_auto_20190831_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='learn_days',
            new_name='add_time',
        ),
    ]
