# Generated by Django 2.2.4 on 2019-08-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0022_auto_20190831_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydaymotto',
            name='audio',
            field=models.FileField(default='default/default.wav', upload_to='motto/audio', verbose_name='audio'),
        ),
    ]
