# Generated by Django 2.2.4 on 2019-08-31 09:10

import Kaldi_speech.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0023_auto_20190831_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='curr_sentence',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(default=Kaldi_speech.models.course_default, on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.Course'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='section',
            field=models.IntegerField(default=-1, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='sentence',
            field=models.IntegerField(default=-1, verbose_name='Sentence'),
        ),
    ]
