# Generated by Django 2.2.4 on 2019-09-01 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0024_auto_20190831_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='score',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='section',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='sentence',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='curr_section',
            field=models.IntegerField(default=-1, verbose_name='current section'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='curr_sentence',
            field=models.IntegerField(default=-1, verbose_name='current sentence'),
        ),
        migrations.AlterField(
            model_name='course',
            name='intro',
            field=models.CharField(default='想说点什么...', max_length=200, verbose_name='introduction'),
        ),
        migrations.CreateModel(
            name='UserAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=90, verbose_name='score')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.Sentence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.User')),
            ],
        ),
    ]
