# Generated by Django 2.2.4 on 2019-09-01 11:02

import Kaldi_speech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0025_auto_20190901_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraudio',
            name='audio',
            field=models.FileField(default='default/default.wav', upload_to=Kaldi_speech.models.useraudio_directory_path, verbose_name='user audio'),
        ),
    ]
