# Generated by Django 2.2.4 on 2019-09-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0026_useraudio_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curr_course',
            field=models.IntegerField(default=-1, verbose_name='current course'),
        ),
    ]
