# Generated by Django 2.2.2 on 2019-10-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0029_auto_20191006_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='learn_days',
            field=models.IntegerField(default=0, verbose_name='学习天数'),
        ),
    ]
