# Generated by Django 2.2.4 on 2019-10-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0030_user_learn_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_learn_time',
            field=models.DateField(auto_now=True, verbose_name='最后学习时间'),
        ),
    ]
