# Generated by Django 2.2.4 on 2019-10-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0031_user_last_learn_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='curr_sentence',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='sec_finished',
            field=models.IntegerField(default=0, verbose_name='章节完成数'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.Course'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='us_speech',
            field=models.FileField(default='default/default.wav', upload_to='verb/', verbose_name='美式发音'),
        ),
        migrations.CreateModel(
            name='UserSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_sentence', models.IntegerField(default=-1, verbose_name='当前例句')),
                ('sen_finished', models.IntegerField(default=0, verbose_name='例句完成数')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.Section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.User')),
            ],
        ),
    ]
