# Generated by Django 2.2.4 on 2019-10-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0032_auto_20191008_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='sec_finished',
        ),
        migrations.RemoveField(
            model_name='usersection',
            name='sen_finished',
        ),
    ]
