# Generated by Django 2.2.4 on 2019-10-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0033_auto_20191008_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='num_sections',
        ),
        migrations.RemoveField(
            model_name='section',
            name='num_sentences',
        ),
    ]
