# Generated by Django 2.2.4 on 2019-10-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0034_auto_20191008_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersection',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
