# Generated by Django 2.2.4 on 2019-10-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0035_auto_20191009_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='usersection',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
