# Generated by Django 2.2.4 on 2019-10-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0036_auto_20191009_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='learn_days',
            field=models.IntegerField(default=1, verbose_name='学习天数'),
        ),
    ]
