# Generated by Django 2.2.2 on 2020-01-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0037_auto_20191010_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='sentence_upper',
            field=models.CharField(default='@default', max_length=200, verbose_name='不带标点大写[无需填写]'),
        ),
    ]
