# Generated by Django 2.2.2 on 2020-04-07 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0038_sentence_sentence_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attend_days',
            field=models.IntegerField(default=0, verbose_name='最长连续打卡时间'),
        ),
        migrations.CreateModel(
            name='UserAttendce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='打卡时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kaldi_speech.User')),
            ],
        ),
    ]
