# Generated by Django 2.2.2 on 2020-04-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0039_auto_20200407_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAttendce',
            new_name='UserAttendance',
        ),
    ]
