# Generated by Django 2.2.2 on 2020-04-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kaldi_speech', '0040_auto_20200407_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attend_days',
        ),
    ]
